// These styles apply to every route in the application
import './globals.css';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Contest Manager',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html className="h-full bg-white">
      <body className="h-full">{children}</body>
    </html>
  );
};

export default RootLayout;
