'use client';

// These styles apply to every route in the application
import './globals.css';
import App from '@/components/App';
import { Amplify, Auth } from 'aws-amplify';
import Login from '@/components/Login';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// const logger = new Logger('Amplify');
// Amplify.Logger.LOG_LEVEL = 'DEBUG';

Amplify.configure({
  aws_project_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_tXpGrpozQ',
  aws_user_pools_web_client_id: '7leskl1tiikiq6qav97f75el45',
  aws_cognito_region: 'us-east-1',
  aws_cognito_identity_pool_id:
    'us-east-1:d2af5156-075b-4cb2-ac7b-ab9fa8ce82f8',
  aws_appsync_graphqlEndpoint:
    'https://dah6jrbtvvgsdopfzn5t5nivnm.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_authenticationType: 'AWS_LAMBDA',
  aws_appsync_region: 'us-east-1',
});

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(true);
  const router = useRouter();

  // TODO create AppRoot component to wrap auth check/login view, remove 'use client' from this file, and uncomment metadata
  useEffect(() => {
    async function checkAuthentication() {
      try {
        const user = await Auth.currentAuthenticatedUser({
          bypassCache: false,
        });
        setUser(user);
      } catch (error) {
        console.log(error);
        setUser(null);
      } finally {
        setLoading(false);
      }
    }

    checkAuthentication();
  }, []);

  if (loading) {
    return (
      <html className="h-full bg-white">
        <body className="h-full">
          <div>Loading...</div>
        </body>
      </html>
    );
  }

  if (user === null) {
    return (
      <html className="h-full bg-white">
        <body className="h-full">
          <Login></Login>
        </body>
      </html>
    );
  }

  return (
    <html className="h-full bg-white">
      <body className="h-full">
        <App
          user={user}
          signOut={async () => {
            router.push('/');
            await Auth.signOut();
            window.location.reload();
          }}>
          {children}
        </App>
      </body>
    </html>
  );
};

export default RootLayout;
